### ISSUE TITLE
Consider changing Bindable to func(interface{}) int

### ISSUE THREAD

**Issue by lolbinarycat** [oakmound/oak#136] opened 2020-08-29 17:13 UTC
As far as I know, no event uses both arguments. It would probably be better to only have one field.

The biggest problem is that of backward compatibility, but I think with the help of some wrapper functions and build options that can be mitigated. This of course would have to wait until v3.

**Comment by lolbinarycat** [comment] 2020-08-29 17:21
I actually think we could change it to `func(interface{}) Response` so people can more easily tell what it returns.

'Response` could also be an alias to `int`, so you wouldn't have to type it all out every time.

**Comment by 200sc** [comment] 2020-08-29 17:23
The ID argument is used to make sure that, if the binding wasn't created with the bound entity visible via a closure, that the entity can be retrieved. This is a particularly important use case because closure bindables can't be manually unbound (https://github.com/oakmound/oak/blob/fd13982054f835ecf900ab41d1fa47b63ddabec6/event/bus.go#L156)

Here are some examples of bindables that use the id argument:
 https://github.com/oakmound/oak/blob/master/collision/onCollision.go#L54
https://github.com/oakmound/oak/blob/fd13982054f835ecf900ab41d1fa47b63ddabec6/examples/pong/core.go#L85
https://github.com/oakmound/oak/blob/fd13982054f835ecf900ab41d1fa47b63ddabec6/examples/top-down-shooter-tutorial/2-shooting/shooting.go#L62
https://github.com/oakmound/oak/blob/fd13982054f835ecf900ab41d1fa47b63ddabec6/examples/cliffracers/core.go#L97
https://github.com/oakmound/oak/blob/fd13982054f835ecf900ab41d1fa47b63ddabec6/examples/sprite-demo/core.go#L106

**Comment by Implausiblyfun** [comment] 2020-08-29 17:27
I guess one could argue that this could be encoded in an interface{} but the use case for handling an id is common enough as stated in previous comments that I think the signature is more usable as is.

**Comment by lolbinarycat** [comment] 2020-08-29 17:55
You know what else is a common use case? handling a button press. So why don't we have `func(int,string,interface{})`. And yes, I am arguing that CIDs should be sent as interfaces like everything else, instead of converted into ints and sent through their own redundant argument. What does that save you? Having to make a type assertion? Is that worth *always* having an unused argument?

**Comment by 200sc** [comment] 2020-08-29 18:04
By design, almost all oak events should verify the entity they are accessing is the correct entity, using the I'd argument. The ones that shouldn't are those that don't directly interact with an entity.

Further, if there was a single interface and you did anything that interacted with both the cid and the payload being sent, as the examples above do, then you'd need to send and assert type structures everywhere just to get the entity the event is acting on. How would you rewrite the top down shooter binding in your plan, @lolbinarycat ?

**Comment by Implausiblyfun** [comment] 2020-08-29 18:04
Im sorry I take back my previous comment as It was misleading. Its been a while since I dug into the event engine and what I said made basically no sense.

200sc's comment actually notes the rationale. :)

**Comment by lolbinarycat** [comment] 2020-08-29 18:26
> By design, almost all oak events should verify the entity they are accessing is the correct entity, using the ID argument. The ones that shouldn't are those that don't directly interact with an entity.
> 
> Further, if there was a single interface and you did anything that interacted with both the cid and the payload being sent, as the examples above do, then you'd need to send and assert type structures everywhere just to get the entity the event is acting on. How would you rewrite the top down shooter binding in your plan, @lolbinarycat ?

Remove line 63. 
In all situation, you should know the id of the entity you are binding to, as it is required for binding. If there is some way for a `Bindable` to be called on an event that was triggered on a different entity, then that's a problem. 

To be honest, I was completely unaware that that's what the int argument was, as it is **completely undocumented**. For something that "all oak events should do", it doesn't seem to get a lot of mentions.

**Comment by 200sc** [comment] 2020-08-29 18:54
It is absolutely documented, at least but not limited to here: https://github.com/oakmound/oak/wiki/A-Platformer#moving-the-character

I can keep looking for more documentation if you want, but I think that if one looked around to find examples that use the id argument, one would always find this same pattern. 

It is not true that no binding uses the id argument. 
It is not true that no binding uses both the id and interface payload arguments. 
There are many situations where you do not know the ID of the entity you are working with, for the reasons I have already stated.

**Comment by lolbinarycat** [comment] 2020-08-29 19:11
> It is absolutely documented, at least but not limited to here: https://github.com/oakmound/oak/wiki/A-Platformer#moving-the-character
That isn't documentation imo. I'm talking about what you see from `go doc` or on https://godoc.org/github.com/oakmound/oak.

> I can keep looking for more documentation if you want, but I think that if one looked around to find examples that use the id argument, one would always find this same pattern.
I don't read examples (most of the time), I read `go doc` and I didn't find any info there.

> It is not true that no binding uses the id argument.
> It is not true that no binding uses both the id and interface payload arguments.
I made both these claims based off of the documentation I read, which didn't even mention the existence of a non-payload argument.

> There are many situations where you do not know the ID of the entity you are working with, for the reasons I have already stated.
Have you? Are you talking about in the link you provided? Because that seemed to be describing (what I would call) a bug.

**Comment by 200sc** [comment] 2020-08-29 19:50
There's clearly miscommunication about why this feature exists, so let me try another thought exercise before doing a braindump. 

Please write a binding that is a top level function (so not a method or closure) that acts on an entity, is used by multiple entities (like both paddles in pong use the same binding in the example above), as a reaction to a mouse press that uses the associated mouse position in it's logic (which doesn't need to be complex or meaningful for this purpose) with just an interface payload argument.

**Comment by 200sc** [comment] 2020-08-29 19:58
Feel free to use this template: 

```
func main () {
  //...
e.Bind(noIDBindable(toplevelFunc), "MouseClickOn")
//...
}

func noIDBindable(newbindable func(interface{}) int) event.Bindable {
    return func(_ int, i interface{}) int {
        return newbindable(I)
    }
}

func toplevelFunc (me interface{}) int {
    mevent, ok := me.(mouse.Event)
    //...
}
```

Typed on my phone so there may be some typos

**Comment by lolbinarycat** [comment] 2020-08-29 20:04
@200sc I can't envision how that function would work *with* an argument. Even the pong example uses a closure. Give me an example of a top level function, and I'll do my best to rewrite it without using the id argument.

If this must exist, it should at least be documented better.

**Comment by 200sc** [comment] 2020-08-29 21:02
Here's an example of this: https://github.com/oakmound/lowrez17/blob/master/game/enemy.go#L75

**Comment by 200sc** [comment] 2020-10-31 18:31
Discussion has stopped. Closing until it reopens.

**Closed by 200sc** 2020-10-31 18:31 UTC
